### ISSUE TITLE
Text literals should use CSS for certain font commands

### ISSUE THREAD

**Issue by runarberg** [runarberg/mathup#78]
When I write `it"proj"` the text is using math-italics instead of true italics, meaning the kerning is all wrong.

![image](https://github.com/runarberg/mathup/assets/3984600/58b56bcf-aaab-4b1e-9750-b4b7f707809c)
![image](https://github.com/runarberg/mathup/assets/3984600/88a07a44-9f6f-487a-b6d2-168053826ccb)

We should take advantage of CSS for the following font commands on text literals:

* `bf` ⇒ `font-weight: bold;`
* `it` ⇒ `font-style: italic`
* `rm` ⇒ `font-family: serif`
* `sf` ⇒ `font-family: sans-serif`
* `tt` ⇒ `font-family: monospace`

We should also support some of the combinations of these, such as:
* `bf it` ⇒ `font-weight: bold; font-style: italic;`
* `bf tt` ⇒ `font-weight: bold; font-family: monospace;`
* `sf bf it` ⇒ `font-family: sans-serif; font-weight: bold; font-style: italic;`

Note that when dealing with font-family we should probably give web authors a way to provide their own fonts. One possibility is to use CSS custom variables:

```
style="font-family: var(--mathup-font-family-monospace) monospace;"
```
 
Web authors can then customize their math fonts like so:

```css
math-up {
  --mathup-font-family-monospace: "My Custom Mono" "Currier New";
  --mathup-font-family-serif: "My Custom Roman" "Times New Roman";
  --mathup-font-family-sans-serf: "My Custom Sans" "Comic Sans";
}
```
